### ISSUE TITLE
Parameter lists in Analytics View

### ISSUE THREAD

**Issue by oliverlux25** [ESA-VirES/Aeolus-Client#13]
In the Analytics View, a clear differentiation should be made between 1D-plots and 2D-plots involving different lists of parameters to be selected by the user. The default setting is the 2D-panel where the Rayleigh or Mie LOS wind is plotted as color-coded bins versus time and altitude. In this 2D-mode, different x- and y-axis parameters should be selectable based on two different lists (x: time, longitude, latitude / y: altitude, range, pressure altitude). At the moment, the same list of parameters is available for both axes. The selection of the color bar parameter (Rayleigh LOS wind speed, Rayleigh signal intensity, Mie SNR, etc.) should be carried out separately, for instance by clicking on the color bar which opens a dropdown list.

For displaying 1D-plots (e.g.  L1B parameters like Rayleigh ground velocity, laser frequency, Mie total ZWC, etc.), a switch is required to change the color-coded 2D-panel to a 1D-panel containing single data points, since the plotted parameters are not altitude-dependent. This switch could be realized, e.g. as a “1D/2D”-button. Upon switching to the 1D-mode, the list of parameters for the y-axis is changed from [altitude, range, pressure altitude] to [Rayleigh ground velocity, laser frequency, Mie total ZWC, etc.], while the x-axis paramter list [time, longitude, latitude] remains unchanged. Also, the color bar should not be displayed in this mode. In case the Split Screen View is used while the 1D-mode is selected, the Globe View should only show the geolocations of the observations (like for the AUX MRC or AUX RRC layers).

The two Analytics View panels should have the same functionality and allow for individual switching between 1D- and 2D-mode.

**Comment by santilland** [comment]
Thank you for the proposed approach! We are considering how to best approach this and will keep in touch on solutions considered.
I think we need to discuss a little how we handle the different product types and the granularity of their parameters in the client.

**Comment by santilland** [comment]
We have introduced a 1D, 2D selection to the analytics panel, i will close this issue.
