### ISSUE TITLE
ADAM albedo map

### ISSUE THREAD

**Issue by Weiles** [ESA-VirES/Aeolus-Client#14]
As defined in the AD-TN, the selection of month and type (Nadir/off-Nadir) of the Albedo map should be based on the instruments mode and on the selected ToI. This functionality needs to be implemented. 

Furthermore, it would be useful to additionally have the information about the month of the albedo map which is shown in the Globe View in the legend label (e.g.: ADAM_albedo-offnadir (October)).

**Comment by Weiles** [comment]
The time selection of the albedo maps is now working properly but the automatic adaption of the map-type (off-nadir or nadir) based on the selected Aeolus data product has not been implemented yet. For L1B, L2A, L2B, L2C, AUX_ISR, AUX_ZWC and AUX_MET files the off-Nadir maps shall be visualised whereas for the calibration files AUX_MRC and AUX_RRC the Nadir maps shall be shown.

**Comment by santilland** [comment]
The automatic adaptation depending on the selected product has also been implemented.
I will close the ticket now, if there are any questions feel free to comment here.
