### ISSUE TITLE
Change saving behavior for plots

### ISSUE THREAD

**Issue by santilland** [ESA-VirES/Aeolus-Client#21]
From #18:
Saving png-pictures for the Analytics View plot panels: It would be clearer if the names of the browser windows were named like: "Opening download upper Panel" and "Opening download lower panel". If possible, it also would be good to specifiy the name of the picture.

Do i understand correctly that the main idea is to help differentiate between which plot is being saved? Would it make sense to introduce two save buttons, once for each graph? From the browser application we can propose a name for the file but if a "Save Dialog" appears depends on the settings of the currently used browser, we can't modify this behavior.

**Comment by Weiles** [comment]
Yes, it would be helpful to introduce two save buttons (one for each plot panel).

**Comment by santilland** [comment]
Added two save buttons now to interface, the proposed file names for the provided files are now also adapted based on the currently selected collection as well as information if the plot being saved is the one on top or bottom.
If there are no further comments on the ticket i will close it by the end of the week.
