### ISSUE TITLE
AUX_ZWC plot vs histogram values

### ISSUE THREAD

**Issue by paoladaulerio** [ESA-VirES/Aeolus-Client#41]
Looking at the AUX_ZWC apparently there is a misalignment between values included in the histogram below compared to the plot above (see screenshot attached)

**Comment by lmar76** [comment]
Why don't set the minimum/maximum values in the histograms equal to the related parameter's minimum/maximum values in the spatio-temporal selection?

**Comment by santilland** [comment]
For now i updated the default extent for this parameters to make sure they have a wider range.
The set extent is saved as configuration so it would be set depending on the first set of data loaded, which is also not ideal.
Initially the ranges in the filter panels were always created by the current data extent but it was pointed out that if there are large outliers one would loose "accuracy" when selecting filters, that is why the set extent is also used for the filter extent.

**Comment by santilland** [comment]
The extent can now be set with the edit button, i think we could close this ticket with this feature becoming available

**Comment by paoladaulerio** [comment]
agreed to close the issue
