### ISSUE TITLE
Error while visualizing mie_HLOS_wind_speed

### ISSUE THREAD

**Issue by lmar76** [ESA-VirES/Aeolus-Client#46]
I was trying to visualize mie_HLOS_wind_speed on Y-axis and time on X-axis (1D plot). The plot was not visible end the error message indicated in the screenshot appeared.

![ghtmp](https://user-images.githubusercontent.com/4036819/47222035-18e57680-d3b6-11e8-8c80-1ee77fd9fd69.png)

**Comment by santilland** [comment]
Hi!
i can reproduce there is an issue of the plot not being rendered correctly, but i am not getting the error on the globe view. I will look into the plot issue first.

**Comment by santilland** [comment]
I found the issue and deployed a fix in the staging area.

**Comment by lmar76** [comment]
Tested. It works, thank you.

**Comment by santilland** [comment]
Fix deployed, closing ticket
