### ISSUE TITLE
Upload issues

### ISSUE THREAD

**Issue by lmar76** [ESA-VirES/Aeolus-Client#51]
We tried to upload an original Aeolus product: AE_OPER_ALD_U_N_1B_20181017T102738034_005411998_000881_0001.TGZ. The upload was completed but the product is not visible on the GUI. We tried again uploading only the DBL file and we could see the product on the GUI.

It is not clear which are the supported product formats. The GUI should be enhanced to indicate them.

**Comment by santilland** [comment]
Added information to label of what files are supported and link to FAQ
![image](https://user-images.githubusercontent.com/4036819/54758737-0bdee480-4bed-11e9-85f2-0543ae16076d.png)
(Will update FAQ)
