### ISSUE TITLE
ZIP64 extension needed

### ISSUE THREAD

**Issue by lmar76** [ESA-VirES/Aeolus-Client#54]
I tried to download a ALD_U_N_1B product between 2018-10-01 and 2018-10-06 in the original file format. During the data processing the following error appeared:

![image](https://user-images.githubusercontent.com/20207042/48554100-c7110d00-e8dd-11e8-8fab-2bc7ba3a22b8.png)

**Comment by santilland** [comment]
If i'm not mistaken this means that the zip would be greater than 4Gb, i guess we would need to discuss what kind of size limits we want to have per user, this could be a challenge when opening the service to a bigger number of users.

**Comment by lmar76** [comment]
Could it be possible to create more than one file covering the selected period of time?

**Comment by santilland** [comment]
In principle it would be possible, but maybe it would make sense to take another approach. If packaging of the files becomes so large that we would start splitting the package maybe we can provide a list of urls to the ADDF which can be used to access all the original files using some kind of download manager.

**Comment by santilland** [comment]
The download of original products has been limited to not allow selections that would create zips over 4GB size.
Closing this thicket as it is no longer relevant.
