### ISSUE TITLE
L2B netcdf download

### ISSUE THREAD

**Issue by Weiles** [ESA-VirES/Aeolus-Client#59]
When downloading L2B products, it would be also important to include the parameters Mie/Rayleigh result_ids which link the accumulation wind results to the different range bins. Otherwise, it is not possible to visualise L2B profile data from the downloaded netcdf file. Moreover, it would be good to include the Parameter l2b_wind_profiles/obs_type which indicates the observation type (clear or cloudy) for each wind result.

**Comment by santilland** [comment]
Following parameters will be included, are these the correct ones?:
mie_wind_result_id
rayleigh_wind_result_id

mie_wind_profile_observation_type
rayleigh_wind_profile_observation_type

**Comment by santilland** [comment]
For now the defined parameters have been added to the staging environment, if there are no further comments the ticket will be closed.

**Comment by Weiles** [comment]
Yes, these Parameters are correct. Thank you for the implementation.
