### ISSUE TITLE
SR-VIR_AE-FUN_01415

### ISSUE THREAD

**Issue by lmar76** [ESA-VirES/Aeolus-Client#68]
According to SR-VIR_AE-FUN_01415:

> It shall be possible to create a high-resolution version of the png described in SR-VIR_AE-FUN_01410

wich, in turn, states:

> It shall be possible for the End-user to save figures and plots from the Globe View as a “publication-ready” graphic file in PNG image format

Currently it is possible to increase the image resolution only for the analytics view. Could it be possible to extend the functionality also the the globe view (as indicated in the requirement)?

**Comment by santilland** [comment]
It was possible to do for the analytics view as it is an in house development. I have looked at the possibilities to do this for the globe view. It might be possible to do (it is difficult to estimate the effort) but it is not provided by the library itself.

**Comment by santilland** [comment]
I created a dedicated ticket #77 for the globe view and will close this ticket if there are no objections.
